Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2021-09, with the labels that each got.

#131 refactor code in triage-status-report script
  Makefile
  tools/triage_status_report.py
Labels: approved, lgtm, size/M

#132 Use skopeo to verify assisted-installer.yaml snapshot
  Jenkinsfile.daily_latest
  Makefile
  requirements.txt
  tools/check_ai_images.py
Labels: approved, lgtm, size/M

#134 Move from pycodestyle to the more powerful flake8
  .pylintrc
  Makefile
  dev-requirements.txt
  setup.cfg
  tools/add_pr_link_to_jira.py
  tools/add_triage_signature.py
  tools/close_by_signature.py
  tools/github_prs_stats.py
  tools/jira_cmd.py
  tools/trace_go_mod_dependencies.py
  tools/update_assisted_installer_yaml.py
  tools/update_default_release_versions_to_latest.py
  tools/update_hash.py
  tools/update_ocp_versions.py
Labels: approved, lgtm, size/M

#135 Order tickets by email domain and username
  tools/triage_status_report.py
Labels: approved, size/XS, lgtm

#136 Enable providing arguments via environment variables
  skipper.env
  skipper.yaml
  tools/triage_status_report.py
Labels: approved, lgtm, size/S

#138 Change users assignment
  release/gittools.py
  release/main.py
  tools/update_default_release_versions_to_latest.py
Labels: approved, lgtm, size/S

#139 Remove files that moved to assisted-service repo
  Jenkinsfile.default_release_update
  tools/update_default_release_versions_to_latest.py
Labels: approved, lgtm, size/XL
