Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2021-12, with the labels that each got.

#165 Empty text messes up JIRA table rendering
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#163 MGMT-8400: use PAT for jira authentication instead of basic auth
  requirements.txt
  skipper.env
  tools/add_pr_link_to_jira.py
  tools/add_triage_signature.py
  tools/close_by_signature.py
  tools/create_testgrid_tickets.py
  tools/create_triage_tickets.py
  tools/github_prs_stats.py
  tools/jira_cmd.py
  tools/release_tickets.py
  tools/triage_status_report.py
  tools/utils.py
Labels: approved, size/L, lgtm

#167 Update image verification script to use new image repository
  assisted-installer.yaml
  tools/assisted_installer_stable_promotion.py
  tools/check_ai_images.py
  tools/update_assisted_installer_yaml.py
  tools/update_hash.py
Labels: approved, lgtm, size/M

#168 Change UI image location to edge-infrastructure org
  assisted-installer.yaml
Labels: approved, size/XS, lgtm

#169 Handle empty host connectivity in get_host_neighbor
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#171 copy OCP bump script from assisted-service
  tools/bump_ocp_releases.py
Labels: approved, size/L, lgtm
