Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2021-10, with the labels that each got.

#140 Apply a couple of fixes to the daily snapshot job.
  Jenkinsfile.daily_repositories_snapshot
Labels: approved, size/XS, lgtm

#142 NO-ISSUE - Retry triage tickets creation on JIRAError exception
  tools/create_triage_tickets.py
Labels: approved, size/XS, lgtm, ok-to-test

#143 Couple of small fixes to the image tagging script
  release/gittools.py
  tools/assisted_installer_stable_promotion.py
Labels: approved, size/XS, lgtm

#141 Add eliorerz to owners
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, needs-ok-to-test

#145 Change default watchers on triage tickets
  OWNERS_ALIASES
  tools/close_by_signature.py
  tools/create_testgrid_tickets.py
  tools/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#146 NO-ISSUE - Retry testgrid tickets creation on JIRAError exception
  tools/create_testgrid_tickets.py
Labels: approved, size/XS, lgtm
