Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-01, with the labels that each got.

#173 Add script for producing CI status reports
  dev-requirements.txt
  requirements.txt
  skipper.env
  tools/ci_status_report.py
Labels: approved, size/L, lgtm

#174 add capi provider repo to CI report
  tools/ci_status_report.py
Labels: approved, size/XS, lgtm

#172 couple of fixes to ocp-bump script
  Dockerfile.assisted-installer-deployment
  requirements.txt
  setup.cfg
  tools/bump_ocp_releases.py
Labels: approved, size/L, lgtm

#175 NO-ISSUE: remove reports dir creation
  .gitignore
  Makefile
Labels: approved, size/XS, lgtm

#176 config git username and email
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S

#178 Add myself as code-approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, needs-ok-to-test

#177 Added bypass-iso-download flag to bump_ocp_releases
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S, ok-to-test

#179 remove CI tickets creation code
  tools/create_testgrid_tickets.py
Labels: approved, size/L, lgtm

#170 MGMT-8400: remove jira basic-auth method
  tools/add_pr_link_to_jira.py
  tools/add_triage_signature.py
  tools/close_by_signature.py
  tools/consts.py
  tools/create_triage_tickets.py
  tools/jira_cmd.py
  tools/release_tickets.py
  tools/triage_status_report.py
  tools/utils.py
Labels: approved, size/L, lgtm

#181 Remove usage of yamlordereddictloader as dicts already ordered
  requirements.txt
  tools/update_assisted_installer_yaml.py
  tools/update_hash.py
Labels: approved, size/XS, lgtm

#183 bump_ocp_releases: fixed pre-release images update
  Dockerfile.assisted-installer-deployment
  requirements.txt
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S

#182 Remove jenkinsfile for automatic repos snapshot
  Jenkinsfile.daily_repositories_snapshot
Labels: approved, lgtm, size/M

#184 bump_ocp_releases: added generate-bundle
  Dockerfile.assisted-installer-deployment
  setup_env.sh
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/M

#185 bump_ocp_releases: install golang 1.16
  Dockerfile.assisted-installer-deployment
Labels: approved, size/XS, lgtm
