Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-03, with the labels that each got.

#196 Change golang version in Dockerfile to 1.17
  Dockerfile.assisted-installer-deployment
Labels: approved, size/XS, lgtm

#197 get vcs ref from latest image
  tools/skopeo.py
  tools/update_assisted_installer_yaml.py
Labels: approved, lgtm, size/M

#199 NO-ISSUE: Remove update before package install
  Dockerfile.assisted-installer-deployment
Labels: approved, size/XS, lgtm, ok-to-test
