Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-10, with the labels that each got.

#304 NO-ISSUE: Don't assign auto-closed tickets to a human
  tools/close_by_signature.py
  tools/create_triage_tickets.py
Labels: approved, lgtm, size/S

#305 TagAnalysis signature - inform user about known/unknown tags
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#306 FlappingValidations more detailed, per-host
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#308 MGMT-11875: Consider operators without conditions unhealthy
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S, needs-ok-to-test
