Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-06, with the labels that each got.

#216 Raise a more graceful error when fields are None
  tools/triage_status_report.py
Labels: approved, lgtm, size/M

#221 add_triage_signature.py: autoclose nissho-ele.co.jp tickets
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm, ok-to-test

#219 Add 'release' makefile target
  Makefile
Labels: approved, size/XS, lgtm

#222 Add platform type to the triage ticket
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#223 Add OpenShift Cluster ID to the ticket description
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#224 Update instructions for JIRA Personal Access Token
  CONTRIBUTING.md
Labels: approved, lgtm, size/S

#225 Fix logs regex and feature-platform syntax
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#232 Update logs URL regex
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#233 Add @vrutkovs to OWNERS_ALIASES under `code-reviewers`
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#235 Escape Jira message formatting specifiers
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#237 MGMT-10849: Create empty requirements file to unblock Jenkins
  requirements-rht.txt
Labels: approved, size/XS, lgtm

#241 Add Red Hat internal repository to the container image if available
  Dockerfile.assisted-installer-deployment
Labels: approved, size/XS, lgtm

#240 Copy "download_jobs" Jenkinsfile from test-infra repository
  Jenkinsfile.download_logs
Labels: approved, lgtm, size/M

#238 Step failure signature fails on negative exit codes
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#226 MGMT-10849: Analyze must-gather using Insights Core
  Dockerfile.assisted-installer-deployment
  requirements-rht.txt
  requirements.txt
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#242 Added new OSInstallationTime signature for hosts that took a long time to write RHCOS to disk
  tools/add_triage_signature.py
Labels: approved, size/L, lgtm

#243 Extract basic info from install-config
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#244 Collect boot mode for host status
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#246 Added new SNOMachineCidrSignature signature for machine cidr that
  tools/add_triage_signature.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#247 Add new NonstandardNetworkType signature and some refactoring
  .dockerignore
  .gitignore
  .pylintrc
  CONTRIBUTING.md
  Dockerfile.assisted-installer-deployment
  Makefile
  dev-requirements.in
  dev-requirements.txt
  pyproject.toml
  requirements.in
  requirements.txt
  setup.cfg
  tools/add_triage_signature.py
  tools/close_by_signature.py
  tools/create_triage_tickets.py
Labels: approved, lgtm, size/XXL

#248 Fix issue with close_by_signature.py after refactor
  tools/add_triage_signature.py
  tools/close_by_signature.py
Labels: approved, lgtm, size/S

#249 Fix create_triage_tickets FailureDescription error
  tools/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#251 Fix create_triage_tickets FailureDescription error (#249)
  tools/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#252 Fix wrong `tools/create_triage_tickets.py` parameter
  tools/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#253 Fix CoreOSInstallerErrorSignature merge issues
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#254 Fix `SNOMachineCidrSignature` merge error
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#256 Fix `SNOMachineCidrSignature` wrong parent constructor call
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm
