Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-11, with the labels that each got.

#309 Avoid false positive `UserManagedNetworkingLoadBalancer` on SNO
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#312 NO-ISSUE: Add `SkipDisks` signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#310 NO-ISSUE: add signature for failed requests leading to failed installation
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#315 Explicit message for when there's no install-config
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S
