Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-07, with the labels that each got.

#258 Add hosts summary to HostsStatusSignature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#259 Add FlappingValidations
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#257 Trigger OCP jobs when bumping versions
  tools/bump_ocp_releases.py
Labels: approved, size/XS, lgtm

#234 triage signatures: added WrongBootOrderSignature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#261 flapping: show validation name instead of the message
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#262 FlappingValidations: bump threshold
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#263 HostsStatusSignature: add a line break for hosts status summary
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#230 signatures: add ReleasePullErrorSignature
  tools/add_triage_signature.py
Labels: approved, lgtm, needs-ok-to-test, size/M

#264 Fix RHCOS image comparison and remove usage of ``rootfs_url``
  requirements.in
  requirements.txt
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/M

#250 Apply code formatting on tools/close_by_signature.py
  Makefile
  tools/close_by_signature.py
Labels: approved, size/L, lgtm

#265 Format triage-report with black
  Makefile
  tools/triage_status_report.py
Labels: approved, lgtm, size/M

#266 Correctly terminate OSInstallationTime(Signature) unknown host green color
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#267 MGMT-11123: allow skipping CCX installations with build-arg
  Dockerfile.assisted-installer-deployment
  Dockerfile.build
  ccx/install.sh
  ccx/requirements-rht.txt
  setup_env.sh
Labels: approved, lgtm, size/M

#271 Extract operator statuses from controller logs
  tools/add_triage_signature.py
Labels: approved, size/L, lgtm

#272 Host storage details better defaults when data is missing
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#274 Automatic detection of Bugzilla 2088346
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#275 NO-ISSUE: Stop releasing BZ tickets
  requirements.in
  requirements.txt
  tools/release_tickets.py
Labels: approved, size/L, lgtm
