Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-08, with the labels that each got.

#276 StaticNetworking signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#277 Signature - better node status reporting
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#278 Master failed rebooting
  tools/add_triage_signature.py
  tools/close_by_signature.py
  triage_resolving_filters.json
Labels: approved, lgtm, size/M

#280 Ticket labels should only be re-applied if the comment was changed
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#279 Fixed StaticNetworking signature that used to fail in case the infraenv static_network_config was None
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#281 Explicit message when there are no nodes in nodes.json
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#282 add signature for hosts IPs
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#283 Signature for Bugzilla 1993243
  requirements.in
  requirements.txt
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#284 Dualstack rDNS MGMT-11651 bug signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#285 MGMT-11688: Skip bump of 4.11 rhcos images
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S

#286 Signature for LVM on RAID bug MGMT-11695
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#287 Rename the `LVMOnRaid` to `InsufficientLVMCleanup`
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#288 Nicer `StaticNetworking` signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#290 MGMT-11688: enable bumping 4.11 RHCOS
  tools/bump_ocp_releases.py
Labels: approved, size/XS, lgtm

#291 MGMT-11723: remove redundant openshit versions section
  assisted-installer.yaml
Labels: approved, size/XS, lgtm

#294 Update Assisted UI to v2.9.1
  assisted-installer.yaml
Labels: approved, size/XS, lgtm

#295 Make DualStackBadRoute an ErrorSignature rather than a Signature
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm
