Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-12, with the labels that each got.

#319 Tell triagers to focus on metal 4.11 multinode tickets
  tools/triage_status_report.py
Labels: approved, size/XS, lgtm

#316 MGMT-12339: Add signature to monitor errors on cleanupInstallDevice
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#320 MGMT-13065: Add expired certificate signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#321 Add signature for missing must gather logs
  tools/add_triage_signature.py
  tools/test_ci_status_report.py
Labels: approved, lgtm, size/S
