Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-02, with the labels that each got.

#187 MGMT-8784: bump versions - skip x.y.z
  tools/bump_ocp_releases.py
Labels: approved, size/XS, lgtm

#188 skip rehearse jobs on CI report
  tools/ci_status_report.py
Labels: approved, size/XS, lgtm

#186 couple of fixes to the release_tickets scripts
  tools/release_tickets.py
Labels: approved, size/XS, lgtm

#189 Make 404 & isoinfo errors more indicative
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S

#191 Change message of CI status job
  tools/ci_status_report.py
Labels: approved, size/XS, lgtm

#192 Add few relevant details to the Install status
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#193 Add default values to host logs collection status and host last checked in time
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#194 Pylinting check_ai_images.py script
  Makefile
  tools/check_ai_images.py
Labels: approved, size/S
