Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2022-09, with the labels that each got.

#298 MGMT-11987: skip OCP 4.12 updates
  tools/bump_ocp_releases.py
Labels: approved, size/XS, lgtm

#297 MGMT-11940: Add signature for user_managed_networking and load-balancer issues
  tools/add_triage_signature.py
Labels: approved, size/L, lgtm

#300 MGMT-11987: fix 4.12 versions getting overridden with 4.11 versions
  tools/bump_ocp_releases.py
Labels: approved, lgtm, size/S

#301 MGMT-11617: only release backend components
  Makefile
  assisted-installer.yaml
  release/main.py
  tools/assisted_installer_stable_promotion.py
Labels: approved, lgtm, size/M

#302 Remove terrible CNIConfigurationError
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#303 NO-ISSUE: Normalize JIRA title when checking for duplicate AITRIAGE
  .editorconfig
  tools/consts.py
  tools/create_triage_tickets.py
  tools/utils.py
Labels: approved, lgtm, size/M
