Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-04, with the labels that each got.

#350 MGMT-13107: Create signature to detect MTU mismatch betwen interface and cluster network
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/S, ok-to-test, jira/valid-reference

#371 Fix duplicated Jira attachments
  tools/jira_client/jira_client_factory.py
Labels: approved, size/XS, lgtm

#373 MGMT-13543: Add signature to detect address change after reboot
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, ok-to-test, size/M, jira/valid-reference

#367 fix references to the new assisted-installer UI repo name
  assisted-installer.yaml
  tools/release_tickets.py
  tools/update_assisted_installer_yaml.py
Labels: approved, size/XS, lgtm
