Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-09, with the labels that each got.

#410 Set DEBUG as log level for clean-old-issues job
  Jenkinsfile.clean_old_issues
Labels: approved, size/XS, lgtm

#411 NO-ISSUE: Increase the number of retries when experiencing difficulties connecting to the Jira server
  tools/triage/clean_old_issues.py
Labels: approved, lgtm, size/M, jira/valid-reference

#413 NO-ISSUE: Remove empovit from code reviewers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#418 NO-ISSUE: Fix inactive watchers removal
  tools/triage/clean_old_issues.py
Labels: approved, size/XS, lgtm, jira/valid-reference
