Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-02, with the labels that each got.

#343 Clarify message for slow OS installation
  tools/add_triage_signature.py
Labels: approved, size/XS, lgtm

#342 Remove SMART column from host storage signature
  tools/add_triage_signature.py
Labels: approved, size/L, lgtm

#340 Apply black for the whole dir of 'tools'
  Makefile
  tools/assisted_installer_stable_promotion.py
  tools/check_ai_images.py
  tools/consts.py
  tools/create_triage_tickets.py
  tools/github_prs_stats.py
  tools/jira_cmd.py
  tools/release_tickets.py
  tools/skopeo_utils.py
  tools/trace_go_mod_dependencies.py
  tools/triage_stats.py
  tools/update_assisted_installer_yaml.py
  tools/update_hash.py
  tools/utils.py
  tools/version_documentation.py
Labels: approved, size/L, lgtm

#344 bump to Python 3.11.0
  .pylintrc
  Dockerfile.assisted-installer-deployment
  dev-requirements.in
  dev-requirements.txt
  release/gittools.py
  release/main.py
Labels: approved, lgtm, size/M

#345 filter-out placeholder tickets in triage status
  tools/triage_status_report.py
Labels: approved, lgtm, size/M

#349 MGMT-13704: Adapt signatures to get host logs both with new and old paths
  tools/add_triage_signature.py
Labels: approved, size/L, lgtm, jira/valid-reference

#351 MGMT-13748: fix git tag on stable promotions
  tools/assisted_installer_stable_promotion.py
Labels: approved, lgtm, size/M, jira/valid-reference

#353 MGMT-13752: Add signatures for existing triage tickets as well
  CONTRIBUTING.md
  Jenkinsfile.download_logs
  README.md
  tools/consts.py
  tools/create_triage_tickets.py
  tools/triage/add_triage_signature.py
  tools/triage/close_by_signature.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
  tools/triage/test_add_triage_signature.py
  tools/utils.py
Labels: approved, size/L, lgtm, jira/valid-reference

#354 MGMT-13752: Fix description not filled in
  tools/triage/add_triage_signature.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
Labels: approved, lgtm, size/M, jira/valid-reference

#356 Fix attachments being redundantly uploaded
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/S

#355 Retry per ticket handling errors
  tools/triage/add_triage_signature.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#358 retry for jira errors when closing tickets
  tools/triage/create_triage_tickets.py
Labels: approved, size/XS, lgtm

#357 append labels instead of resetting
  tools/triage/add_triage_signature.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
Labels: approved, lgtm, size/S
