Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-07, with the labels that each got.

#392 sno cannot have etcd in hostname
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/M

#389 Add signature for cases where the cluster moved from installing pending user action to error
  tools/triage/add_triage_signature.py
  tools/triage/triage_resolving_filters.json
Labels: approved, lgtm, size/M

#394 Treat < 30 size manifests as empty
  tools/triage/add_triage_signature.py
Labels: approved, size/XS, lgtm

#396 MGMT-15343: dependabot group updates
  .github/dependabot.yml
Labels: approved, lgtm, size/M, jira/valid-reference

#397 Don't hide the more controller warnings message inside the code block at the bottom
  tools/triage/add_triage_signature.py
Labels: approved, size/XS, lgtm
