Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-03, with the labels that each got.

#352 MGMT-13442 add generic issue filtering for triage
  Makefile
  dev-requirements.in
  dev-requirements.txt
  pyproject.toml
  release/gittools.py
  release/main.py
  requirements.txt
  tests/__init__.py
  tests/tools/__init__.py
  tests/tools/jira/test_jira_api.py
  tests/tools/jira/test_jira_client_factory.py
  tests/tools/jira/test_jira_dryrun_client.py
  tests/tools/triage/fixtures/example_filters.json
  tests/tools/triage/test_add_triage_signature.py
  tests/tools/triage/test_filters.py
  tools/assisted_installer_stable_promotion.py
  tools/github_prs_stats.py
  tools/jira_client/__init__.py
  tools/jira_client/consts.py
  tools/jira_client/jira_api.py
  tools/jira_client/jira_client_factory.py
  tools/jira_client/jira_dryrun_client.py
  tools/jira_cmd.py
  tools/release_tickets.py
  tools/skopeo_utils.py
  tools/trace_go_mod_dependencies.py
  tools/triage/__init__.py
  tools/triage/add_triage_signature.py
  tools/triage/close_by_signature.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
  tools/triage/filters.py
  tools/triage/triage_resolving_filters.json
  tools/triage_stats.py
  tools/triage_status_report.py
  tools/update_assisted_installer_yaml.py
  tools/update_hash.py
  tools/version_documentation.py
  triage_resolving_filters.json
Labels: approved, lgtm, ok-to-test, size/XXL

#359 MGMT-13667: Signature to detect user login to the cluster hosts.
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, ok-to-test, size/M, jira/valid-reference

#361 Reduce warnings emitted for currently acceptable access
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/M

#338 MGMT-13401: store cluster logs as Jira attachments
  Jenkinsfile.download_logs
  requirements.in
  requirements.txt
  skipper.yaml
  tests/tools/triage/test_attach_logs_in_jira.py
  tools/triage/add_triage_signature.py
  tools/triage/attach_logs_in_jira.py
  tools/triage/create_triage_tickets.py
  tools/utils.py
Labels: approved, size/L, lgtm, jira/valid-reference

#360 retry filter instantation if jira GET issue fails
  Makefile
  tools/triage/filters.py
Labels: approved, size/XS, lgtm

#363 bump jira client to v3.4.1
  requirements.in
  requirements.txt
Labels: approved, lgtm, size/M

#364 Split long triage status reports
  requirements.in
  requirements.txt
  tools/triage_status_report.py
Labels: approved, lgtm, size/M

#365 Fix arguments for jira methods
  tests/tools/jira/test_jira_dryrun_client.py
  tools/jira_client/jira_api.py
  tools/jira_client/jira_dryrun_client.py
  tools/jira_cmd.py
  tools/triage/create_triage_tickets.py
Labels: approved, lgtm, size/M

#368 MGMT-13999: Change triage focus to multi node clusters
  tools/triage_status_report.py
Labels: approved, lgtm, size/S, jira/valid-reference
