Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-06, with the labels that each got.

#379 snapshot of repositories' current git revisions
  assisted-installer.yaml
Labels: approved, size/XS, lgtm

#382 add rccrdpccl and javipolo as approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#381 NO-ISSUE: Match only ssh/console logins to avoid false positives
  tools/triage/add_triage_signature.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#383 NO-ISSUE: Remove deleted hosts from metadata
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/M, jira/valid-reference

#384 NO-ISSUE-fix-further-downloader-issue: Fixing a small bug discovered…
  tools/triage/ticket_search/jira_attachment_downloader.py
  tools/triage/utils/extraction/gzip_file_extractor.py
Labels: approved, size/XS, lgtm

#386 No issue add podman and docker shortcuts
  Makefile
  README.md
Labels: approved, lgtm, size/S

#385 MGMT-14989: Document how to fetch JIRA_ACCESS_TOKEN for triage search users
  README.md
Labels: approved, lgtm, size/M, jira/valid-reference

#387 Match more possible controller log file names
  tools/triage/add_triage_signature.py
Labels: approved, size/XS, lgtm

#390 NO-ISSUE: Fix DeletedHostsStatusSignature so it only triggers when needed
  tools/triage/add_triage_signature.py
Labels: approved, size/XS, lgtm, jira/valid-reference
