Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-01, with the labels that each got.

#323 Allow overriding remote repo URL in Jenkins
  Jenkinsfile.download_logs
Labels: approved, size/XS, lgtm

#325 New ControllerWarnings signature to show controller warnings
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#329 MGMT-13191: fix image tagging of hotfix releases
  tools/assisted_installer_stable_promotion.py
  tools/skopeo_utils.py
  tools/update_assisted_installer_yaml.py
Labels: approved, lgtm, size/M

#330 Remove duplicated mount of netrc
  skipper.yaml
Labels: approved, size/XS

#327 AITRIAGE-4849: added a signature for missing OSTree pivot
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#328 New MachineConfigDaemonErrorExtracting signature to check for machine…
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#331 workaround to must-gather sig
  tools/add_triage_signature.py
Labels: approved, lgtm, size/S

#333 Add eranco74 as approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#332 Add ControllerFailedToStart signature
  tools/add_triage_signature.py
Labels: approved, lgtm, size/M

#335 Remove CI reporting code
  requirements.in
  requirements.txt
  skipper.env
  tools/ci_status_report.py
  tools/test_ci_status_report.py
Labels: approved, size/L, lgtm

#336 Fix image tagging and git tagging
  tools/assisted_installer_stable_promotion.py
Labels: approved, lgtm, size/S

#337 NO-ISSUE: Try to make triage report relient to errors
  tools/triage_status_report.py
Labels: approved, lgtm, size/S, jira/valid-reference

#339 Tell triagers to focus on OCP 4.12 tickets
  tools/triage_status_report.py
Labels: approved, size/XS, lgtm

#341 Fix ccx installation missing openssl
  Dockerfile.assisted-installer-deployment
Labels: approved, size/XS, lgtm
