Repository openshift-assisted/assisted-installer-deployment, pull requests merged in 2023-10, with the labels that each got.

#420 SNO missing rendered-master MC
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/M

#419 Look for multiple hosts holding the same VIP
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/M

#415 MGMT-13402: Using Jira attachments to produce ticket signatures
  Jenkinsfile.download_logs
  tests/tools/triage/utils/test_jira_remote_archive_querier.py
  tests/tools/triage/utils/test_local_nested_archive_extractor.py
  tools/triage/add_triage_signature.py
  tools/triage/clean_old_issues.py
  tools/triage/common.py
  tools/triage/create_triage_tickets.py
  tools/triage/exceptions.py
  tools/triage/utils/extraction/jira_attachment_querier/__init__.py
  tools/triage/utils/extraction/jira_attachment_querier/jira_remote_archive_querier.py
  tools/triage/utils/extraction/jira_attachment_querier/local_nested_archive_extractor.py
Labels: approved, lgtm, size/XXL, jira/valid-reference

#427 MGMT-13402: Add missing arguments
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/S, jira/valid-reference

#426 NO-ISSUE: Add my account an approval capability
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#428 NO-ISSUE: Add missing arguments
  tools/triage/add_triage_signature.py
Labels: approved, lgtm, size/S, jira/valid-reference
